version: '3'

volumes:
  pgdata:

services:
  cards-api:
    build:
      context: .
      dockerfile: docker/python/Dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - cards-postgres
    restart: on-failure
  cards-postgres:
    image: postgres:9.5
    environment:
      POSTGRES_USER: cards
      POSTGRES_DB: cards
      POSTGRES_PASSWORD: cards
      POSTGRES_HOST_AUTH_METHOD: "trust"
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432

